In [29]:
import pandas as pd
import os
import pandas as pd
import numpy as np

In [30]:
df = pd.read_excel("dados\sapore_funcionario.xlsx")  
df.head()

,Nome,DataAdmissao,DataDemissao,Email,Celular,CodigoFuncao,Descricao,CodigoCliente,RazaoSocial
0,LETICIA PEREIRA DA SILVA,2025-01-14,2025-02-11,PRISCILA.CLAUDIA@SAPORE.COM.BR,12988817947,234,OFICIAL DE SERVICOS,5849,SAPORE SA
1,GABRIELA DIAS TEIXEIRA,2025-01-14,2025-04-01,gabrieladiasteixeira467@gmail.com,12996397477,34,ATENDENTE,5849,SAPORE SA
2,VALESCA GUIMARAES PAULISTA MARQUES,2025-01-14,2025-03-31,VALESCAGPAULISTA96@GMAIL.COM,24993045528,234,OFICIAL DE SERVICOS,5849,SAPORE SA
3,CHRISSIE DAMARES DE ALMEIDA SCHUINDT,2025-01-14,2025-01-25,damareschrissie@gmail.com,43984557514,234,OFICIAL DE SERVICOS,5849,SAPORE SA
4,JONATAN DOMINGOS DO NASCIMENTO,2025-01-14,2025-04-16,DOMINGOSJONATAN643@GMAIL.COM,21975752988,234,OFICIAL DE SERVICOS,5849,SAPORE SA

In [31]:
df.columns

Index(['Nome', 'DataAdmissao', 'DataDemissao', 'Email', 'Celular',
       'CodigoFuncao', 'Descricao', 'CodigoCliente', 'RazaoSocial'],
      dtype='object')

In [32]:
df['DataAdmissao'].min()

Timestamp('2025-01-02 00:00:00')

In [33]:
df['DataAdmissao'].max()

Timestamp('2026-03-19 00:00:00')

In [34]:
df.shape

(4848, 9)

In [39]:
import unicodedata
import re

def normalizar_texto(texto):
    if pd.isna(texto):
        return ""

    # minúsculo
    texto = texto.lower()

    # remover acento
    texto = unicodedata.normalize('NFKD', texto).encode('ascii', 'ignore').decode('utf-8')

    # remover caracteres especiais
    texto = re.sub(r'[^a-z0-9\s]', '', texto)

    # remover espaços extras
    texto = re.sub(r'\s+', ' ', texto).strip()

    return texto

In [40]:
def preparar_dataframe(df):

    df_copy = df.copy()
    df_copy['Descricao'] = df_copy['Descricao'].apply(normalizar_texto)

    df_copy['DataAdmissao'] = pd.to_datetime(df_copy['DataAdmissao'], errors='coerce')
    df_copy['DataDemissao'] = pd.to_datetime(df_copy['DataDemissao'], errors='coerce')

    hoje = pd.Timestamp.now()
    df_copy['fim'] = df_copy['DataDemissao'].fillna(hoje)

    df_copy['meses'] = (
        (df_copy['fim'].dt.year - df_copy['DataAdmissao'].dt.year) * 12 +
        (df_copy['fim'].dt.month - df_copy['DataAdmissao'].dt.month)
    )

    return df_copy

In [41]:

df_test = preparar_dataframe(df)

df_test[['Nome','Descricao','DataAdmissao', 'DataDemissao', 'meses']].head(10)

,Nome,Descricao,DataAdmissao,DataDemissao,meses
0,LETICIA PEREIRA DA SILVA,oficial de servicos,2025-01-14,2025-02-11,1
1,GABRIELA DIAS TEIXEIRA,atendente,2025-01-14,2025-04-01,3
2,VALESCA GUIMARAES PAULISTA MARQUES,oficial de servicos,2025-01-14,2025-03-31,2
3,CHRISSIE DAMARES DE ALMEIDA SCHUINDT,oficial de servicos,2025-01-14,2025-01-25,0
4,JONATAN DOMINGOS DO NASCIMENTO,oficial de servicos,2025-01-14,2025-04-16,3
5,CAMILA APARECIDA MARINHO JESUS,atendente,2025-01-15,2025-07-13,6
6,GEOVANIO TAVARES DE SOUZA,oficial de servicos,2025-01-15,2025-02-24,1
7,ALCIONETE MARQUES DE BRITO,oficial de servicos,2025-01-15,2025-01-23,0
8,ADRIANA MARIA ROSA LIMA,oficial de servicos,2025-01-15,2025-05-21,4
9,NAIARA VITORIA FERREIRA DE ALMEIDA,atendente,2025-01-16,2025-03-28,2

In [46]:
cozinheiros = df_test[(df_test['Descricao'] == 'cozinheiro i') & (df_test['meses'] <= 3)]

In [47]:
cozinheiros

,Nome,DataAdmissao,DataDemissao,Email,Celular,CodigoFuncao,Descricao,CodigoCliente,RazaoSocial,fim,meses
371,PATRICIA REGINA MELO DE LIMA,2025-09-22,2025-09-23,FARIASMELOPATRICIA12@GMAIL.COM,51519851422,221,cozinheiro i,5849,SAPORE SA,2025-09-23 00:00:00.000000,0
381,VALDILENE FERREIRA DE ARAUJO,2025-09-27,2025-10-08,VALDILENEF975@GMAIL.COM,15981678175,221,cozinheiro i,5849,SAPORE SA,2025-10-08 00:00:00.000000,1
384,ODETE CONCEICAO BARBOSA GARCIA,2025-10-01,2025-10-14,ODETEBARBOSA4@GMAIL.COM,19992022206,221,cozinheiro i,5849,SAPORE SA,2025-10-14 00:00:00.000000,0
390,VERIDIANA ALMERINA GOMES BARRETO,2025-10-06,2025-12-01,VERIDIANAGOMES444@GMAIL.COM,31319841943,221,cozinheiro i,5849,SAPORE SA,2025-12-01 00:00:00.000000,2
395,IDALECIO SILVA LIMA,2025-10-07,2026-01-05,IDALESTESILVALIMA@GMAIL.COM,35997159003,221,cozinheiro i,5849,SAPORE SA,2026-01-05 00:00:00.000000,3
...,...,...,...,...,...,...,...,...,...,...,...
4663,SIMONE APARECIDA FERREIRA,2026-03-05,NaT,MONEFERREIRAMONEFERREIRA1986@GMAIL.COM,15997566446,1453,cozinheiro i,5849,SAPORE SA,2026-03-30 15:47:14.894138,0
4664,TATIANA SANTOS MATEUS,2026-03-05,NaT,TATIANAMATEUS8@GMAIL.COM,24999419541,1453,cozinheiro i,5849,SAPORE SA,2026-03-30 15:47:14.894138,0
4665,DEBORA SOARES RODRIGUES,2026-03-05,NaT,DEBORAARODRIGUES67@GMAIL.COM,51989927526,1453,cozinheiro i,5849,SAPORE SA,2026-03-30 15:47:14.894138,0
4666,MARIA EDICLEIDE DOS SANTOS FREIRE,2026-03-05,NaT,CLEIDESANTOSNOEMY@GMAIL.COM,7998106052,1453,cozinheiro i,5849,SAPORE SA,2026-03-30 15:47:14.894138,0
4706,DAISE ALEXANDRA REIS DE OLIVEIRA,2025-07-16,2025-08-26,DAISEOLIVEIRA458@GMAIL.COM,51981249108,1453,cozinheiro i,5849,SAPORE SA,2025-08-26 00:00:00.000000,1